#!/usr/bin/env python3
"""Generate a PyTorch reference (oracle) + a pytest correctness scaffold.

Pure templating: this script only WRITES text. It never imports or executes the
operator under test. The emitted test imports your kernel wrapper (run later
under pytest) and compares it against a PyTorch reference with
`torch.testing.assert_close` over a shape x dtype grid.

Usage:
    python gen_pytorch_oracle.py --op add \
        --wrapper-module my_ops --wrapper-fn add \
        --shapes 1024 4096 4095 --dtypes float16 float32 \
        --out test_add_correctness.py

`--op` must be in the registry below (extend it for new ops). If your op is not
listed, pass --op custom and edit the emitted `reference(...)` by hand.
"""

from __future__ import annotations

import argparse

# Op -> (reference expression using torch, n_inputs, notes)
# reference is a string evaluated in the emitted test where `xs` is the input list.
REGISTRY: dict[str, tuple[str, int, str]] = {
    "add": ("xs[0] + xs[1]", 2, "elementwise"),
    "mul": ("xs[0] * xs[1]", 2, "elementwise"),
    "relu": ("torch.relu(xs[0])", 1, "elementwise"),
    "gelu": ("torch.nn.functional.gelu(xs[0])", 1, "elementwise"),
    "silu": ("torch.nn.functional.silu(xs[0])", 1, "elementwise"),
    "softmax": ("torch.softmax(xs[0], dim=-1)", 1, "reduction; needs other=-inf"),
    "sum_last": ("xs[0].sum(dim=-1)", 1, "reduction"),
    "mean_last": ("xs[0].mean(dim=-1)", 1, "reduction"),
    "rms_norm": (
        "xs[0] * torch.rsqrt(xs[0].pow(2).mean(-1, keepdim=True) + 1e-6)",
        1,
        "reduction; fp32 accumulate",
    ),
    "flip_last": ("torch.flip(xs[0], dims=[-1])", 1, "layout"),
    "pixel_unshuffle": (
        "torch.nn.functional.pixel_unshuffle(xs[0], downscale_factor=2)",
        1,
        "layout; needs 4D NCHW input divisible by 2",
    ),
    "custom": ("xs[0]  # TODO: edit this reference by hand", 1, "edit me"),
}

TEMPLATE = '''\
"""Auto-generated correctness scaffold for `{op}` ({notes}).
Generated by gen_pytorch_oracle.py — edit the reference / shapes as needed.
"""
import itertools

import pytest
import torch

import {wrapper_module} as _under_test  # your kernel wrapper module

pytestmark = pytest.mark.skipif(
    not torch.cuda.is_available(), reason="CUDA not available"
)

DEVICE = "cuda"
SHAPES = {shapes!r}
DTYPES = [getattr(torch, name) for name in {dtypes!r}]
TOL = {{
    torch.float32: dict(atol=1e-5, rtol=1e-5),
    torch.float16: dict(atol=1e-3, rtol=1e-3),
    torch.bfloat16: dict(atol=1e-2, rtol=1e-2),
}}

N_INPUTS = {n_inputs}


def reference(xs):
    return {reference}


@pytest.mark.parametrize("shape,dtype,contiguous", list(itertools.product(
    SHAPES, DTYPES, [True, False])))
def test_correctness(shape, dtype, contiguous):
    shape = shape if isinstance(shape, tuple) else (shape,)
    xs = [torch.randn(*shape, dtype=dtype, device=DEVICE) for _ in range(N_INPUTS)]
    if not contiguous:
        if len(shape) < 2:
            pytest.skip("non-contiguous needs >=2D")
        xs = [x.transpose(-1, -2) for x in xs]
    expected = reference(xs)
    got = _under_test.{wrapper_fn}(*xs)
    torch.testing.assert_close(got, expected, **TOL[dtype])
'''


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--op", required=True, choices=sorted(REGISTRY))
    p.add_argument(
        "--wrapper-module", required=True, help="python module of your wrapper"
    )
    p.add_argument("--wrapper-fn", required=True, help="wrapper function name")
    p.add_argument(
        "--shapes",
        nargs="+",
        default=["1024", "4096", "4095"],
        help="ints (1D) or comma tuples like 64,128",
    )
    p.add_argument("--dtypes", nargs="+", default=["float16", "float32"])
    p.add_argument("--out", default=None, help="output path; default stdout")
    args = p.parse_args(argv)

    reference, n_inputs, notes = REGISTRY[args.op]

    shapes: list = []

    for s in args.shapes:
        shapes.append(tuple(int(x) for x in s.split(",")) if "," in s else int(s))

    code = TEMPLATE.format(
        op=args.op,
        notes=notes,
        wrapper_module=args.wrapper_module,
        wrapper_fn=args.wrapper_fn,
        shapes=shapes,
        dtypes=args.dtypes,
        n_inputs=n_inputs,
        reference=reference,
    )

    if args.out:
        with open(args.out, "w", encoding="utf-8") as f:
            f.write(code)

        print(f"wrote {args.out}")
    else:
        print(code)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
