#!/usr/bin/env python3
"""Generate a PyTorch reference test scaffold with shape x dtype x layout matrix.

Produces a complete pytest file that tests your kernel wrapper against a
PyTorch reference over multiple shapes, dtypes, and contiguity layouts.

Includes MERE/MARE precision metrics and non-contiguous input testing.

Usage:
    python scripts/gen_pytorch_oracle.py --op add \\
        --wrapper-module my_ops --wrapper-fn add \\
        --shapes 1024 4096 4095 --dtypes float16 float32 \\
        --out test_add_correctness.py

    # For a 2D operator:
    python scripts/gen_pytorch_oracle.py --op softmax \\
        --wrapper-module my_ops --wrapper-fn softmax \\
        --shapes 128,1024 4096,1024 100,333 --dtypes float16 float32 \\
        --out test_softmax_correctness.py

Built-in op registry: add, mul, relu, gelu, silu, softmax, sum_last,
    mean_last, rms_norm, copysign, rad2deg, deg2rad, lgamma, custom.
"""
from __future__ import annotations

import argparse

REGISTRY: dict[str, tuple[str, int, str]] = {
    "add": ("xs[0] + xs[1]", 2, "elementwise binary"),
    "mul": ("xs[0] * xs[1]", 2, "elementwise binary"),
    "relu": ("torch.relu(xs[0])", 1, "elementwise unary"),
    "gelu": ("torch.nn.functional.gelu(xs[0])", 1, "elementwise unary"),
    "silu": ("torch.nn.functional.silu(xs[0])", 1, "elementwise unary"),
    "softmax": ("torch.softmax(xs[0], dim=-1)", 1, "reduction"),
    "sum_last": ("xs[0].sum(dim=-1)", 1, "reduction"),
    "mean_last": ("xs[0].mean(dim=-1)", 1, "reduction"),
    "rms_norm": (
        "xs[0] * torch.rsqrt(xs[0].pow(2).mean(-1, keepdim=True) + 1e-6)",
        1,
        "reduction + elementwise",
    ),
    "copysign": ("torch.copysign(xs[0], xs[1])", 2, "elementwise binary"),
    "rad2deg": ("torch.rad2deg(xs[0])", 1, "elementwise unary"),
    "deg2rad": ("torch.deg2rad(xs[0])", 1, "elementwise unary"),
    "lgamma": ("torch.lgamma(xs[0])", 1, "elementwise unary"),
    "custom": ("xs[0]  # TODO: edit this reference by hand", 1, "edit me"),
}

TEMPLATE = '''\
"""Auto-generated correctness scaffold for `{op}` ({notes}).
Generated by gen_pytorch_oracle.py — edit shapes / reference as needed.

Test matrix: {n_shapes} shapes x {n_dtypes} dtypes x 2 layouts (contiguous + transposed)
Total test cases: {total_tests}
"""
import itertools

import pytest
import torch

import {wrapper_module} as _under_test

pytestmark = pytest.mark.skipif(
    not torch.cuda.is_available(), reason="CUDA not available"
)

DEVICE = "cuda"
SHAPES = {shapes!r}
DTYPES = [getattr(torch, name) for name in {dtypes!r}]
TOL = {{
    torch.float32: dict(atol=1e-5, rtol=1e-5),
    torch.float16: dict(atol=1e-3, rtol=1e-3),
    torch.bfloat16: dict(atol=1e-2, rtol=1e-2),
}}

N_INPUTS = {n_inputs}


def reference(xs):
    """PyTorch reference implementation."""
    return {reference}


def compute_error_metrics(result, ref):
    """Compute MERE and MARE for precision validation."""
    diff = (result.float() - ref.float()).abs()
    denom = ref.float().abs().clamp(min=1e-8)
    mere = (diff / denom).mean().item()
    mare = (diff / denom).max().item()
    return mere, mare


# --- Correctness matrix ---

@pytest.mark.parametrize("shape,dtype", list(itertools.product(SHAPES, DTYPES)))
def test_correctness(shape, dtype):
    shape = shape if isinstance(shape, tuple) else (shape,)
    xs = [torch.randn(*shape, dtype=dtype, device=DEVICE) for _ in range(N_INPUTS)]
    expected = reference(xs)
    got = _under_test.{wrapper_fn}(*xs)
    torch.testing.assert_close(got, expected, **TOL[dtype])


# --- Non-contiguous input tests ---

@pytest.mark.parametrize("dtype", DTYPES)
def test_non_contiguous_transposed(dtype):
    """Verify kernel handles transposed (non-contiguous) input."""
    shape = (64, 128)
    base = [torch.randn(*shape, dtype=dtype, device=DEVICE) for _ in range(N_INPUTS)]
    xs = [x.t() for x in base]
    expected = reference(xs)
    got = _under_test.{wrapper_fn}(*xs)
    torch.testing.assert_close(got, expected, **TOL[dtype])


@pytest.mark.parametrize("dtype", DTYPES)
def test_non_contiguous_strided(dtype):
    """Verify kernel handles strided slice input."""
    shape = (128, 256)
    base = [torch.randn(*shape, dtype=dtype, device=DEVICE) for _ in range(N_INPUTS)]
    xs = [x[::2, ::3] for x in base]
    expected = reference(xs)
    got = _under_test.{wrapper_fn}(*xs)
    torch.testing.assert_close(got, expected, **TOL[dtype])


# --- Precision metrics (informational) ---

def test_precision_metrics():
    """Report MERE/MARE for float16 and float32 on a medium shape."""
    shape = SHAPES[len(SHAPES) // 2] if len(SHAPES) > 1 else SHAPES[0]
    shape = shape if isinstance(shape, tuple) else (shape,)
    for dtype_name in {dtypes!r}:
        dtype = getattr(torch, dtype_name)
        xs = [torch.randn(*shape, dtype=dtype, device=DEVICE) for _ in range(N_INPUTS)]
        expected = reference(xs)
        got = _under_test.{wrapper_fn}(*xs)
        mere, mare = compute_error_metrics(got, expected)
        print(f"  {{dtype_name}}: MERE={{mere:.3e}} MARE={{mare:.3e}}")
'''


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--op", required=True, choices=sorted(REGISTRY))
    p.add_argument("--wrapper-module", required=True, help="python module of your wrapper")
    p.add_argument("--wrapper-fn", required=True, help="wrapper function name")
    p.add_argument(
        "--shapes", nargs="+", default=["1024", "4096", "4095"],
        help="ints (1D) or comma tuples like 64,128"
    )
    p.add_argument("--dtypes", nargs="+", default=["float16", "float32"])
    p.add_argument("--out", default=None, help="output path; default stdout")
    args = p.parse_args(argv)

    reference, n_inputs, notes = REGISTRY[args.op]

    shapes: list = []
    for s in args.shapes:
        shapes.append(tuple(int(x) for x in s.split(",")) if "," in s else int(s))

    total_tests = len(shapes) * len(args.dtypes) + 2 * len(args.dtypes) + 1

    code = TEMPLATE.format(
        op=args.op,
        notes=notes,
        wrapper_module=args.wrapper_module,
        wrapper_fn=args.wrapper_fn,
        shapes=shapes,
        dtypes=args.dtypes,
        n_inputs=n_inputs,
        reference=reference,
        n_shapes=len(shapes),
        n_dtypes=len(args.dtypes),
        total_tests=total_tests,
    )

    if args.out:
        with open(args.out, "w", encoding="utf-8") as f:
            f.write(code)
        print(f"wrote {args.out} ({total_tests} test cases)")
    else:
        print(code)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
