name: pytest
on: [push, pull_request]
jobs:
  pytest:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: [self-hosted, linux, x64, nvidia, ninetoothed]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -e .[all]
          python3 -m pip install -r requirements.txt
      - name: Test with pytest
        run: |
          python3 -m pytest --doctest-modules --junitxml=junit/test-results.xml --cov=ninetoothed --cov-report=xml --cov-report=html
